### ISSUE TITLE
Patch for sjlj exceptions

### ISSUE THREAD

**Issue by jeroenooms** [niXman/mingw-builds#409]
There is an annoying bug in mingw-w64 v3 related to sjlj exceptions. The bug was fixed in v4, unfortunately we need to stick with v3 for now. The [patch](http://pastebin.com/k4dLndkw) is really simple, would it be possible to add this patch to the automatic build process for `--rt-version=v3`?

**Comment by niXman** [comment]
`https://github.com/thirdwing/Rtools/blob/R_extsoft/script_by_rubenvb/patches/mingw-w64-3.3.0.patch` - bad link, 404.

**Comment by jeroenooms** [comment]
Oh shit, private repo :D Here a copy: http://pastebin.com/k4dLndkw

**Comment by niXman** [comment]
Now is Ok. I'll try to aply this patch for v3.

**Comment by niXman** [comment]
As I can see this patch is already here: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/v3.x/tree/mingw-w64-crt/misc/mingw_getsp.S

**Comment by niXman** [comment]
diff: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/b43f78cb4150752ea7f02b2eb14dfc2cfd30e5ff/

**Comment by jeroenooms** [comment]
Oh that is odd. Is this patch part of v3.3.0 release or later? Which exact version of mingw-w64 does mingw-builds use when setting `--rt-version=v3` ?

**Comment by niXman** [comment]
> Which exact version of mingw-w64 does mingw-builds use when setting --rt-version=v3 ?

`v3.x` branch: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/v3.x/tree/

**Comment by jeroenooms** [comment]
Oh okay so it changes. I should probably write down which commit of v3.x was used when building then, in case I want to reproduce the exact same tool chain later.

**Comment by niXman** [comment]
Closed.

**Comment by jeroenooms** [comment]
We just built our software using `--rt-version=v3` but it still seems to suffer from the sjlj bug. Are you sure that the mingw-builds scripts use the latest trunk of v3? Or does it use the latest stable (i.e. v3.3.0 which still has the bug)?

**Comment by Andne** [comment]
If you specify `--rt-version=v3` then the script will checkout v3 and use that.  However, if the `mingw-w64` folder already exists in the `src` directory, then the checkout does not occur, and the script uses whichever version you currently have checked out.  There is also the argument `--update-sources` that is supposed to force an update to the latest version for anything that uses git or svn as the source.  That should include the mingw64 runtime.

As a side note, in order to use a specific release, you have to specify the full release (i.e. `--rt-version=v3.3.0`).  In that case, the script will download the tar.bz2 file for that release and use it instead.  Unfortunately, it looks like 3.3.0 is the latest release of the v3 line, so there doesn't appear to be a release available that contains the fix you need.

**Comment by jeroenooms** [comment]
Thanks. This confirms my fear that the sjlj bug we are experiencing has not properly been fixed yet in mingw-w64 :(
