### ISSUE TITLE
GCC 6.2 branch

### ISSUE THREAD

**Issue by joeparkerz** [niXman/mingw-builds#431]
Hi,

Make a gcc 6.2 branch...

**Comment by carlkl** [comment]
This repository doesn't seem to be in line with latest mingw-builds binaries based on gcc-6.3. These binaries are using a patch called
 `gcc-6.1-disable-weak-refs.patch`

Is this patch the same as 
`0016-disable-weak-refs-in-libstdc++.patch` found in https://github.com/Alexpux/MINGW-packages ?

**Comment by karel-m** [comment]
@niXman is there any chance to have the build scripts used for building mingw-build's gcc-6.3.0 toolchain binaries?

**Comment by niXman** [comment]
Hi,

@karel-m I have a local copy of the project that contains the necessary changes and patches for building gcc-6.3 and gcc-7. But I can not merge my local changes with the upstream project because the auto-merge does not work and it is needed to merge manually. But I do not have free time for this now.
I could send you an archive of my local copy of the scripts so that you can build gcc-6.3 and gcc-7 by yourself, but it would be nice if you, or anyone else, could make the merging manually =)

**Comment by karel-m** [comment]
@niXman I would definitelly appreciate if you could provide me with the latest version you have mentioned. I do not want to promise in advance that I will be able to fix merge conflicts but I can try :)

If your latest version is only able to build gcc6/7 I would even propose creating a new separate repo e.g. `mingw-builds6` where you can drop build scripts for pre-6 versions and point (in README) those who want to build gcc4/5 to the old repo `mingw-builds`

**Comment by niXman** [comment]
> If your latest version is only able to build gcc6/7

No, it is mingw-builds project with additional fixes/rules/patches.

Ok, I will prepare the arhive and attach into this issue...

**Comment by carlkl** [comment]
@niXman, what about putting it into an extra branch?

**Comment by stephenwhittle** [comment]
This would be really great to see. Currently the build-from-git package on MSYS2 is still set up for GCC 6.3.0 and I need 7+ to test some of the C++1z functionality. Happy to help test a version supporting 7+.

**Comment by carlkl** [comment]
@niXman's gcc-7.1.0 builds have been announced here: http://www.mail-archive.com/mingw-w64-public@lists.sourceforge.net/msg13372.html

**Comment by niXman** [comment]
Sorry for the delay, archive in attachments.
[mingw-builds.zip](https://github.com/niXman/mingw-builds/files/987827/mingw-builds.zip)

**Comment by niXman** [comment]
> BTW: gendef.exe is missing in the new binary builds

Hmm..

**Comment by niXman** [comment]
> BTW: gendef.exe is missing in the new binary builds

I see. Please create the another issue.

**Comment by White-Tiger** [comment]
niXman, I really love your work, but it has become quite a hassle to stay in sync...
You had newer releases on the MSYS side for a while _(before that, your SF used to be the latest of all possible builds)_ but now they're lacking behind SF once more...

So currently I guess it's all about the merge issue? Because you're not building the MSYS binaries yourself but someone else / a build bot does?
Won't the merge conflict get worse the longer you wait? GCC for Windows seems to be generally quite some patchwork with lots of conflicts but they don't seem to get any better.

**Comment by niXman** [comment]
@White-Tiger, You seem to have misunderstood me...
The only problem that existed was the lack of free time. Only for this reason I have accumulated a local heap of changes, some of which I committed. So I broke myself the possibility to merge the changes...

But at the moment the problem is solved and for the last two weeks I have released two releases:

https://github.com/niXman/mingw-builds/releases/tag/v-4.3.0
https://github.com/niXman/mingw-builds/releases/tag/v-4.3.1
