### ISSUE TITLE
x86_64 posix seh: `Pthreads are required to build libgomp`

### ISSUE THREAD

**Issue by Prince213** [niXman/mingw-builds#498]
I'm trying to build static gcc with this command `./build --mode=gcc-9.2.0 --jobs=2 --no-multilib --no-extras --static-gcc --rt-version=v7.0.0 --with-default-msvcrt=ucrt --enable-languages=c,c++ --buildroot=/e/mingw920 --threads=posix --exceptions=seh --arch=x86_64`. And the script failed when building libgomp.
[config.log](https://github.com/niXman/mingw-builds/files/4152148/config.log) is attached.
```
/e/mingw920/x86_64-920-posix-seh-rt_v700-s/build/gcc-9.2.0/./gcc/xgcc -B/e/mingw920/x86_64-920-posix-seh-rt_v700-s/build/gcc-9.2.0/./gcc/ -L/mingw64/x86_64-w64-mingw32/lib -L/mingw64/mingw/lib -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/mingw/include -B/mingw64/x86_64-w64-mingw32/bin/ -B/mingw64/x86_64-w64-mingw32/lib/ -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/x86_64-w64-mingw32/sys-include   -fno-checking -o conftest.exe -g -O2 -pipe -fno-ident -I/e/mingw920/x86_64-920-posix-seh-rt_v700-s/mingw64/opt/include -I/e/mingw920/prerequisites/x86_64-zlib-static/include -I/e/mingw920/prerequisites/x86_64-w64-mingw32-static/include   conftest.c -lpthread  >&5
E:\mingw920\x86_64-920-posix-seh-rt_v700-s\mingw64\bin\ld.exe: E:/mingw920/x86_64-920-posix-seh-rt_v700-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0xc6d): undefined reference to `_setjmp'
collect2.exe: error: ld returned 1 exit status
configure:15353: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU Offloading and Multi Processing Runtime Library"
| #define PACKAGE_TARNAME "libgomp"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "GNU Offloading and Multi Processing Runtime Library 1.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL "http://www.gnu.org/software/libgomp/"
| #define PACKAGE "libgomp"
| #define VERSION "1.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define LT_OBJDIR ".libs/"
| #define STDC_HEADERS 1
| #define TIME_WITH_SYS_TIME 1
| #define STRING_WITH_STRINGS 1
| #define HAVE_PTHREAD_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_SEMAPHORE_H 1
| #define HAVE_SYS_TIME_H 1
| /* end confdefs.h.  */
| #include <pthread.h>
|          void *g(void *d) { return NULL; }
| int
| main ()
| {
| pthread_t t; pthread_create(&t,NULL,g,NULL);
|   ;
|   return 0;
| }
configure:15356: error: Pthreads are required to build libgomp
```

**Comment by niXman** [comment]
This error indicates that libpthread.a previously been built by the compiler using SJLJ exceptions:
> E:/mingw920/x86_64-920-posix-seh-rt_v700-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0xc6d): undefined reference to `_setjmp'

please remove the `E:/mingw920/x86_64-920-posix-seh-rt_v700-s` dir and start again.

**Comment by Prince213** [comment]
I've cleaned the entire build directory and started everything from the beginning, but I still got the same error.

**Comment by niXman** [comment]
make sure the environment variables are not changed. for example, there should be nothing like "export CC=g++" etc

**Comment by niXman** [comment]
or just reinstall MSYS2

**Comment by Prince213** [comment]
I had successfully built other toolchains before, so I guess the MSYS2 side is fine. Also I didn't do anything when the scripts were running.

**Comment by Prince213** [comment]
But anyway I'll just reinstall MSYS2 and see what will happen, hopefully that'll solve the problem.

**Comment by niXman** [comment]
sorry, but I have no other idea...

**Comment by niXman** [comment]
@Prince213 try to rebuild using this cmdline: `./build --mode=gcc-9.2.0 --jobs=2 --no-multilib --no-extras --static-gcc --rt-version=v7.0.0 --with-default-msvcrt=ucrt --enable-languages=c,c++ --buildroot=/e/mingw920 --threads=posix --exceptions=seh --arch=x86_64 --bootstrap`

**Comment by Prince213** [comment]
Why `--bootstrap`?

**Comment by jrmoore** [comment]
I'm experiencing the same right now with the following selection of options:

`./build --mode=gcc-11.1.0 --arch=x86_64 --buildroot=/builds --exceptions=seh --no-multilib --static-gcc --jobs=8 --rt-version=v9.0.0 --with-default-msvcrt=ucrt --threads=win32 --march-x64=core2 --mtune-x64=skylake --enable-languages=c,c++ --no-extras`

I tried switching to POSIX threading, but it doesn't seem to change anything, `winpthreads` is actually built after the C runtime, no idea what the problem could be. I'm using the scripts from the develop branch, its tip as of 10h ago.

**Comment by jrmoore** [comment]
While the problem seems to be related to the `winpthreads` library (e.g., modifying the build scripts to build `gmp`, `isl`, `mpc` and `mpfr` in-tree doesn't work either), I wonder if the way in which the C runtime is linked to has something to do with it.

The log for that part (libgomp in the gcc build) shows undefined references to `__imp___iob_func` and `_setjmp` when linking to `libpthread.a` , but it wasn't built with a SJLJ toolchain, my MSYS2 environment was pristine and the the toolchain downloaded to start it all is `x86_64-7.2.0-release-posix-seh-rt_v5-rev1`.

Digging into the `__imp___iob_func` took me to the C runtime itself, with those things being defined in `stdio.h`, I'm going to try to build the toolchain using the old MSVCRT instead of UCRT and see if that changes anything (or trying the v9 git branch of mingw-w64), it could be a bug in how that's handled. I'll also try to find another SEH build to use instead as the initial toolchain, in case there was a problem with the v5-rev1 of 7.2.0.

I'm attaching the artifacts created during a `winpthreads` build, in case someone can see something there: 
[x86_64-winpthreads-v9.0.0.zip](https://github.com/niXman/mingw-builds/files/6879859/x86_64-winpthreads-v9.0.0.zip)

_EDIT: **Changing to the older C runtime leads to a successful build** both with the scripts as they are and with `gmp`, `isl`, `mpc` and `mpfr` in-tree. I'll keep on experimenting and report back whatever I find._

**Comment by niXman** [comment]
just try `--bootstrap` with clean scripts from the `develop` branch

**Comment by niXman** [comment]
> Why `--bootstrap`?

@Prince213 any luck?

**Comment by jrmoore** [comment]
> just try `--bootstrap` with clean scripts from the `develop` branch

Why `--bootstrap` though? It's not an option the scripts recognize at the moment, there's `--bootstrapall`, which leads to the same problem and `--no-bootstrap` , which also leads there (the test for `pthreads` fails for `libatomic` too if building with many jobs).

Without using any of those options my build is being bootstrapped though, because I'm also using `--static-gcc`  (build script at line 257):

```
		--static-gcc)
			BOOTSTRAPING=yes
			LINK_TYPE_GCC=$LINK_TYPE_STATIC
			GCC_DEPS_LINK_TYPE=$LINK_TYPE_STATIC
			BUILD_SHARED_GCC=no
			LINK_TYPE_SUFFIX=static
```

On another note, switching mingw-w64 to the v9 dev. branch instead of using the stable v9 release doesn't change the outcome, nor does using a different starting toolchain. I'm able to build a GCC 11.1.0, binutils 2.36.1, Mingw-w64 v9.x/v9.0.0 toolchain without issues, as long as `--with-default-msvcrt=msvcrt` is used instead of `--with-default-msvcrt=ucrt` or the switch is omitted altogether since it defaults to MSVCRT.

It'll be a while, because the machine building the toolchain is a tad slow, but I'll go back to the beginning and start building from GCC 9 up and see which combination gets stuck. I recall enabling LTO for the build was also a problem at some point, but I didn't wrote down the configure line.

I'll let you guys know what comes of it.

**Comment by Prince213** [comment]
> @Prince213 any luck?

This time with more errors:
```
D:\mingw-gcc-11.2.0\x86_64-1120-posix-seh-rt_v9-s\mingw64\bin\ld.exe: D:/mingw-gcc-11.2.0/x86_64-1120-posix-seh-rt_v9-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0x4e2): undefined reference to `__imp___iob_func'
D:\mingw-gcc-11.2.0\x86_64-1120-posix-seh-rt_v9-s\mingw64\bin\ld.exe: D:/mingw-gcc-11.2.0/x86_64-1120-posix-seh-rt_v9-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0x727): undefined reference to `__imp___iob_func'
D:\mingw-gcc-11.2.0\x86_64-1120-posix-seh-rt_v9-s\mingw64\bin\ld.exe: D:/mingw-gcc-11.2.0/x86_64-1120-posix-seh-rt_v9-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0xc72): undefined reference to `_setjmp'
D:\mingw-gcc-11.2.0\x86_64-1120-posix-seh-rt_v9-s\mingw64\bin\ld.exe: D:/mingw-gcc-11.2.0/x86_64-1120-posix-seh-rt_v9-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0xfd2): undefined reference to `__imp___iob_func'
D:\mingw-gcc-11.2.0\x86_64-1120-posix-seh-rt_v9-s\mingw64\bin\ld.exe: D:/mingw-gcc-11.2.0/x86_64-1120-posix-seh-rt_v9-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-rwlock.o):rwlock.c:(.text+0x20a): undefined reference to `__imp___iob_func'
D:\mingw-gcc-11.2.0\x86_64-1120-posix-seh-rt_v9-s\mingw64\bin\ld.exe: D:/mingw-gcc-11.2.0/x86_64-1120-posix-seh-rt_v9-s/mingw64/mingw/lib/../lib/libpthread.a(libwinpthread_la-cond.o):cond.c:(.text+0xd0): undefined reference to `__imp___iob_func'
```

Commandline: `./build --mode=gcc-11.2.0 --arch=x86_64 --buildroot=/d/mingw-gcc-11.2.0 --exceptions=dwarfseh --bootstrapall --no-multilib --no-extras --static-gcc --jobs=4 --rt-version=trunk --with-default-msvcrt=ucrt --threads=posix --bin-compress --enable-languages=c,c++`

**Comment by Prince213** [comment]
> The log for that part (libgomp in the gcc build) shows undefined references to __imp___iob_func and _setjmp when linking to libpthread.a
> the the toolchain downloaded to start it all is x86_64-7.2.0-release-posix-seh-rt_v5-rev1.

@jrmoore maybe related to this: https://github.com/mirror/mingw-w64/commit/af149abc81550de19a80fba0f9d0e89fe4d01f2f

Consider updating mingw-w64 version of your toolchain (the one used to build).

**Comment by jrmoore** [comment]
> Consider updating mingw-w64 version of your toolchain (the one used to build).

I tried it already, I've gone through quite a lot of different starting toolchains (the default one, one built using these scripts (either Win32 or POSIX threaded), TDM's, possibly some other, can't recall). The one I'm using now was built using:

`--jobs=8 --buildroot=/z --mode=gcc-11.2.0 --rt-version=v9 --with-default-msvcrt=msvcrt --threads=posix --arch=x86_64 --march-x32=native --march-x64=native --march-x32=native --mtune-x64=native --enable-languages=c,c++ --exceptions=seh --static-gcc --no-multilib --no-extras`

Those `march`es are just so the resulting toolchain speeds things up a bit by default if at all possible, for the testing toolchain I'm OK with it.

There's certainly a way to build a toolchain using `ucrt`, there's a whole repo in MSYS2 for it, I just need to find the time to look into what the problem is. Damn days are too short haha.

> @jrmoore maybe related to this: mirror/mingw-w64@af149ab

Thanks for the reference, I'll look into it.

**Comment by vszakats** [comment]
Bumped into the `_setjmp` issue. It requires UCRT, linking pthread statically, x86_64 and either the latest (as of this writing) [Homebrew mingw-w64](https://github.com/Homebrew/homebrew-core/blob/f5b7df43237be7faba53696fbbece7cda213200a/Formula/mingw-w64.rb) or [debian:testing mingw-w64](https://packages.debian.org/bookworm/mingw-w64). [Latest llvm-mingw](https://github.com/mstorsjo/llvm-mingw/releases/tag/20220323) is not affected. Same with clang and gcc.

Minimal example:
```shell
# clang
/usr/local/opt/llvm/bin/clang -target x86_64-w64-mingw32 --sysroot /usr/local/opt/mingw-w64/toolchain-x86_64 -fuse-ld=lld \
  test.c -D_UCRT -Wl,-Bstatic -lpthread -Wl,-Bdynamic -lucrt
# gcc
x86_64-w64-mingw32-gcc -dumpspecs | sed 's/-lmsvcrt/-lucrt/g' > gcc-specs-ucrt
x86_64-w64-mingw32-gcc -specs=gcc-specs-ucrt \
  test.c -D_UCRT -Wl,-Bstatic -lpthread -Wl,-Bdynamic -lucrt
```

```c
/* test.c */
#include <pthread.h>
int main(void) {
  pthread_rwlock_t lock;
  pthread_rwlock_init(&lock, NULL);
  return 0;
}
```

```console
ld.lld: error: undefined symbol: _setjmp
>>> referenced by ../src/thread.c:1518
>>>               libpthread.a(libwinpthread_la-thread.o):(pthread_create_wrapper)
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```
```console
/usr/local/Cellar/mingw-w64/10.0.0_1/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: /usr/local/Cellar/mingw-w64/10.0.0_1/toolchain-x86_64/lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o): in function `pthread_create_wrapper':
/private/tmp/mingw-w64-20220506-7546-1q81cpu/mingw-w64-v10.0.0/mingw-w64-libraries/winpthreads/build-x86_64/../src/thread.c:1518: undefined reference to `_setjmp'
collect2: error: ld returned 1 exit status
```
