### ISSUE TITLE
LTO breaks binutils build

### ISSUE THREAD

**Issue by Prince213** [niXman/mingw-builds#555]
While working on #498, I came across this when building binutils:
```
C:\msys64\tmp\cci0ZbK6.ltrans0.ltrans.o:<artificial>:(.text+0x5382): undefined reference to `strndup'
```
Which caused build failure of at least dwp.exe and ld-new.exe.
The commandline is `./build --mode=gcc-11.2.0 --arch=i686 --buildroot=/d/mingw-gcc-11.2.0 --exceptions=dwarfseh --use-lto --bootstrapall --no-multilib --no-extras --static-gcc --jobs=4 --rt-version=trunk --with-default-msvcrt=ucrt --threads=posix --bin-compress --enable-languages=c,c++`

> I recall enabling LTO for the build was also a problem at some point, but I didn't wrote down the configure line.

@jrmoore

**Comment by jrmoore** [comment]
Similar outcome here, I left the machine building at `j1` to have ordered logs overnight and the error I got with LTO is also in binutils, undefined references to `stpcpy`.

From what I could gather when I looked into it, it seems to be an old bug that was kind of diagnosed several years ago but was left open and unattended: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66014

> The issue seems to be related to libiberty's implementation of stpcpy being replaced with the GCC builtin and then causing linker errors due to that symbol not being defined when attempting to link lto-plugin.

The source code has changed significantly since then, but I'd say the root of the issue still applies although at different stages. For example, in my build this night the problem arose when building `objdump`. If I get the time I'll try delving into it and either selectively disabling LTO for affected binaries or getting to the root of it.

[configure.log](https://github.com/niXman/mingw-builds/files/6975056/configure.log)
[make.log](https://github.com/niXman/mingw-builds/files/6975072/make.log)
